BudgetApp
Santosh-Konappanavar/BudgetApp pull request #1
Opened 2023-07-19 09:50 UTC by Santosh-Konappanavar

### In this PR I did the following:
* [ ]  I created a Ruby on Rails application that allows the user to:
* register and log in, so that the data is private to them.
* introduce new transactions associated with a category.
* see the money spent on each category.
 
 ### Interactions
* [ ]  Splash screen
* A simple page with the name of your app (yes, you need to choose one), and links to the - - - sign up and login pages.
* [ ]  Sign up and login pages
* The user should be able to register in the app with full name, email and password (all mandatory).
* The user can log into the app using email and password.
* If the user is not logged in, they can't access pages that require the user to be logged in (all the pages described below).
* [ ]  Home page (categories page)
* When the user logs in, they are presented with the categories page.
* For each category, the user can see their name, icon and the total amount of all the transactions that belong to that category.
* When the user clicks (or taps) on a category item, the application navigates to the transactions page for that category.
* There is a button "add a new category" at the bottom that brings the user to the page to create a new category.
* [ ]  Transactions page
* For a given category, the list of transactions is presented, ordered by the most recent.
* At the top of the page the user could see the total amount for the category (sum of all of the amounts of the transactions in that category).
* There is a button "add a new transaction" at the bottom that brings the user to the page to create a new transaction.
* When the user clicks on the "Back" button (<), the user navigates to the home page.
* [ ]  "Add a new category" page
* The user fills out a form to create a new category, indicating their name and icon (both mandatory).
* The user clicks (or taps) the "Save" button to create the new category, and is taken to the home page on success.
* When the user clicks on the "Back" button (<), the user navigates to the home page.
* [ ]  "Add a new transaction" page
* The user fills out a form to create a new transaction with:
  
* Name (mandatory)
* Amount (mandatory)
* categories (mandatory at least one)
* The user clicks (or taps) the "Save" button to create the new transaction, and is taken to the transactions page for that category.
* When the user clicks on the "Back" button (<), the user navigates to the transactions page for that category.
* [ ] Write tests
* [ ]  Live video link

2023-07-19 15:03 UTC, joel-kalema requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @Santosh-Konappanavar 
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![TN6](https://user-images.githubusercontent.com/57408419/242633152-ef9bf425-5bec-4c19-bada-7713cd7e55f2.gif)


## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Follow GitHub flow :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me @joel-kalema  when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-19 15:03 UTC, joel-kalema commented on app/controllers/users/omniauth_callbacks_controller.rb
> +  # devise :omniauthable, omniauth_providers: [:twitter]
You did a good job working on BudgetApp 🥇, however, you need to fix some parts

- [ ] Currently, when we are login, we are able to see all `Categories` and `transactions` created by another user 😢, Kindly make sure all users have their own `categories` and `transactions` and only the user can see his own `category` and `transaction`
> I think if other users login into the app, they will be able to see my `Categories` and `transactions` which is not following the structure of the [schema](https://github.com/microverseinc/curriculum-rails/blob/main/capstone/rails_capstone.md#:~:text=for%20your%20project,Project%20documentation)

2023-07-19 15:03 UTC, joel-kalema commented on app/views/categories/index.html.erb
> +    <%= link_to "Add a New Category", new_category_path, class: "add_transaction_btn" %>
- [ ] Kindly, make sure you added the button to delete `Category`,  you may take an example from this:

![Screenshot 2023-07-19 161607](https://github.com/Santosh-Konappanavar/BudgetApp/assets/57408419/28692c29-0718-4946-b393-f496e0bece27)

2023-07-19 15:03 UTC, joel-kalema commented on app/views/layouts/application.html.erb
>    </body>
- [ ] As we are working on a mobile app, It could be better if you fix your margins to stick to the design and for a good user experience.

![Screenshot 2023-07-19 162304](https://github.com/Santosh-Konappanavar/BudgetApp/assets/57408419/fda83c03-12cc-438f-b6b1-41c48298b5d5)

- [ ] Alo so your `signin` and `signup` pages. Kindly fix the `<input/>` margins, and I'll suggest you put the login button at the bottom but not into the navbar 👍 

![Screenshot 2023-07-19 162926](https://github.com/Santosh-Konappanavar/BudgetApp/assets/57408419/009791ea-75d8-4e0a-9b3f-923801baeab2)

- [ ] [OPTIONAL] For a better user experience, I'll suggest you put your `<` button to the left:

![Screenshot 2023-07-19 163410](https://github.com/Santosh-Konappanavar/BudgetApp/assets/57408419/aa5ea748-71e5-4aab-8690-495bd6ee78f8)

2023-07-19 15:03 UTC, joel-kalema commented on README.md
- [ ] Kindly, fix the link to your `LICENSE`, to make your README more professional 👍 

![Screenshot 2023-07-19 170121](https://github.com/Santosh-Konappanavar/BudgetApp/assets/57408419/1c2e252e-f284-4d9e-a683-a23a5045479a)

2023-07-20 12:25 UTC, ichala approved these changes
Hi Student  ,
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  
 
![68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966](https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif)

# To Highlight 💪🏻

- Changes Implemented ✔️ 


 Good job implementing the requirements  :+1: Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Optional Suggestions  :

- N/A


**********
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag  ichala in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-20 12:52 UTC, merged